"""initialize database

Revision ID: 2bbe960c6a3d
Revises: c940fc78a5b0
Create Date: 2022-12-06 18:55:57.407403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbe960c6a3d'
down_revision = 'c940fc78a5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('hs_code', sa.String(length=10), nullable=False),
    sa.Column('hs_description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('hs_code')
    )
    op.create_table('country',
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('trade_relationship', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('date_dim',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('daySuffix', sa.String(length=2), nullable=False),
    sa.Column('weekdayname', sa.String(length=10), nullable=False),
    sa.Column('weekdayname_short', sa.String(length=3), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('monthname', sa.String(length=10), nullable=False),
    sa.Column('monthname_short', sa.String(length=3), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('quartername', sa.String(length=6), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mmyyyy', sa.String(length=6), nullable=False),
    sa.Column('monthyear', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('itc_staff',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=3), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('case_groups',
    sa.Column('group_id', sa.String(length=5), nullable=False),
    sa.Column('product_from_countries', sa.String(length=150), nullable=False),
    sa.Column('product_id', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('commissioners',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('commissioner_name', sa.String(length=150), nullable=False),
    sa.Column('term_begin_date', sa.Date(), nullable=False),
    sa.Column('term_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['term_begin_date'], ['date_dim.date'], ),
    sa.ForeignKeyConstraint(['term_end_date'], ['date_dim.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('determinations',
    sa.Column('investigation_number', sa.String(length=10), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('determination', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['hearing_date'], ['date_dim.date'], ),
    sa.PrimaryKeyConstraint('investigation_number', 'phase')
    )
    op.create_table('investigations',
    sa.Column('investigation_number', sa.String(length=11), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('product_id', sa.String(length=3), nullable=False),
    sa.Column('group_id', sa.String(length=5), nullable=False),
    sa.Column('investigation_title', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['country.country_code'], ),
    sa.ForeignKeyConstraint(['group_id'], ['case_groups.group_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('investigation_number')
    )
    op.create_table('petitioners',
    sa.Column('firm_name', sa.String(length=150), nullable=False),
    sa.Column('group_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['case_groups.group_id'], ),
    sa.PrimaryKeyConstraint('firm_name', 'group_id')
    )
    op.create_table('scopes',
    sa.Column('group_id', sa.String(length=5), nullable=False),
    sa.Column('hs_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['case_groups.group_id'], ),
    sa.ForeignKeyConstraint(['hs_code'], ['commodities.hs_code'], ),
    sa.PrimaryKeyConstraint('group_id', 'hs_code')
    )
    op.create_table('staff_assigned',
    sa.Column('group_id', sa.String(length=5), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['case_groups.group_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['itc_staff.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'staff_id')
    )
    op.create_table('publications',
    sa.Column('pub_no', sa.String(length=4), nullable=False),
    sa.Column('investigation_number', sa.String(length=11), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['investigation_number'], ['investigations.investigation_number'], ),
    sa.PrimaryKeyConstraint('pub_no')
    )
    op.create_table('representations',
    sa.Column('group_id', sa.String(length=5), nullable=False),
    sa.Column('petitioner_name', sa.String(length=150), nullable=False),
    sa.Column('law_firm_name', sa.String(length=150), nullable=False),
    sa.Column('law_lead', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['case_groups.group_id'], ),
    sa.ForeignKeyConstraint(['law_firm_name'], ['law_firms.firm_name'], ),
    sa.ForeignKeyConstraint(['law_lead'], ['law_firms.lead'], ),
    sa.ForeignKeyConstraint(['petitioner_name'], ['petitioners.firm_name'], ),
    sa.PrimaryKeyConstraint('group_id', 'petitioner_name', 'law_firm_name')
    )
    with op.batch_alter_table('law_firms', schema=None) as batch_op:
        batch_op.alter_column('firm_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('lead',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('law_firms', schema=None) as batch_op:
        batch_op.alter_column('lead',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('firm_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.drop_table('representations')
    op.drop_table('publications')
    op.drop_table('staff_assigned')
    op.drop_table('scopes')
    op.drop_table('petitioners')
    op.drop_table('investigations')
    op.drop_table('determinations')
    op.drop_table('commissioners')
    op.drop_table('case_groups')
    op.drop_table('products')
    op.drop_table('itc_staff')
    op.drop_table('date_dim')
    op.drop_table('country')
    op.drop_table('commodities')
    # ### end Alembic commands ###
